// app/layout.tsx
import { Geist, Geist_Mono } from "next/font/google";
import { CartProvider } from './storecontect/Contectapi';

import { Providers } from './provider'


import './globals.css';
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

// Metadata for the page (now works as part of the Server Component)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// No "use client" directive here, everything is server-rendered
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <CartProvider>
            <div className="app-container">
              <Navbar />
              {children}
              <Footer />
            </div>
          </CartProvider>
        </Providers>
      </body>
    </html>
  );
}
